# Numpy

In [ ]:
import numpy as np

## 1. version

It is a Attribute.

Which is presesnt inside the numpy library

It is used to check the latest version of the numpy

> ***syntax :- np.__version__***

In [ ]:
np.__version__

'2.0.2'

## 2. array()

It is the function.

Which is present inside the numpy library.

It is used to convert list into array.

> ***Syntax :- np.arry(list_var / list_collection)***


In [ ]:
l=[1,2,3]
ar=np.array(l)
print(type(l))
print(type(ar))

<class 'list'>
<class 'numpy.ndarray'>


## 3. dtype

It is an Attribute.

Which is present inside the array module in numpy library.

It is used to check, what type of data is present inside the array.

> ***Syntax :- arr_var.dtype***

Priority : If you have multiple types of data then priority given in below format

> object (set>dict)> str > complex > float > int > bool


In [ ]:


a=np.array([1,True,12])
print(a)
print(a.dtype)

a=np.array([1,True,1.5])
print(a)
print(a.dtype)

a=np.array([1+2j,True,1.5])
print(a)
print(a.dtype)

a=np.array(['a',1+2j,True,1.5])
print(a)
print(a.dtype)

a=np.array([{1,2,2,3},'a',1+2j,True,1.5])
print(a)
print(a.dtype)



[ 1  1 12]
int64
[1.  1.  1.5]
float64
[1. +2.j 1. +0.j 1.5+0.j]
complex128
['a' '(1+2j)' 'True' '1.5']
<U64
[{1, 2, 3} 'a' (1+2j) True 1.5]
object


## 4. ndim

It is an Attribute.

Which is present inside the array module in numpy library.

It return the No. of dimensions of the array.

> ***Syntax :- arr_var.ndim***

In [ ]:
a=np.array([1,2,3])
print(a.ndim)

1


## 5. ndmin

It is an Parameter/variable of array().

Which is present inside the array module in numpy library.

It convert uni-dimensional array to multi-dimensional array.

> ***Syntax :- np.array([CDT/List_var],ndmin = no.of dimension)***

In [ ]:
a=np.array([1,2,3],ndmin=6)
print(a.ndim)
print(a)

6
[[[[[[1 2 3]]]]]]


## 6. shape

It is an Attribute.

Which is present inside the array module of numpy library.

It return the No. of rows and columns of the array.

> ***Syntax :- arr_var.shape***

In [ ]:
a1=np.array([1,2,3,4])
print(a1)
print(a1.dtype)
print(a1.shape)

[1 2 3 4]
int64
(4,)


In [ ]:
a2=np.array([[1,5+3j,3],
             [4,5,6],
             [7,8,9]])
print(a2)
print(a2.dtype)
print(a2.shape)

[[1.+0.j 5.+3.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]
complex128
(3, 3)


In [ ]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],

            [[True,12,13],
             [14,'15',16],
             [17,{18,13},19]]])
print(a3)
print(a3.dtype)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[True 12 13]
  [14 '15' 16]
  [17 {18, 13} 19]]]
object
(2, 3, 3)


## 7. reshape()

It is an function. Which is present inside the array module in numpy library.

It is used to change the rows and columns in existing array.

> ***Syntax :-***

>***a) arr-var.reshape(no_of_value)***

>***b) arr-var.reshape(row,column)***

>***c) arr-var.reshape(dimension,row,column)***

In [ ]:
a4=np.array([[1,2,3,1],
             [4,5,6,2],
             [7,8,9,3],
             [7,8,9,3]])
print(a4)
print(a4.dtype)
print(a4.shape)

print('------------')
a4=a4.reshape(2,2,4)
print(a4)
print(a4.dtype)
print(a4.shape)

print('------------')
a4=a4.reshape(1,8,2)
print(a4)
print(a4.dtype)
print(a4.shape)

print('------------')
a4=a4.reshape(4,2,2)
print(a4)
print(a4.dtype)
print(a4.shape)


[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]
 [7 8 9 3]]
int64
(4, 4)
------------
[[[1 2 3 1]
  [4 5 6 2]]

 [[7 8 9 3]
  [7 8 9 3]]]
int64
(2, 2, 4)
------------
[[[1 2]
  [3 1]
  [4 5]
  [6 2]
  [7 8]
  [9 3]
  [7 8]
  [9 3]]]
int64
(1, 8, 2)
------------
[[[1 2]
  [3 1]]

 [[4 5]
  [6 2]]

 [[7 8]
  [9 3]]

 [[7 8]
  [9 3]]]
int64
(4, 2, 2)


## 8. reshape(-1)

It is an function. Which is present inside the array module in numpy library.

It convert multi-dimensional array to uni-dimensional array

> ***Syntax :- arr-var.reshape(-1)***

In [ ]:
print('------------')
a4=a4.reshape(-1)
print(a4)
print(a4.dtype)
print(a4.shape)

------------
[1 2 3 1 4 5 6 2 7 8 9 3 7 8 9 3]
int64
(16,)


## 9. arange()

It is an function. Which is present inside the numpy library.

It is used **to generate sequence** of the number b/w the specified limit.

> ***Syntax :- arr-var = np.arange(sv , ev+1 , updation )***

In [ ]:
a6=np.arange(1,11,2)
print(a6)

a6=np.arange(50,0,-5).reshape(1,5,2)
print(a6)

[1 3 5 7 9]
[[[50 45]
  [40 35]
  [30 25]
  [20 15]
  [10  5]]]


## 10. linspace()

It is an function. Which is present inside the numpy library.

It is used to generate equally spaced value b/w the specified limit.

> ***Syntax :- arr-var = np.linspace(sv , ev , no_of_parts )***

In [ ]:
a7=np.linspace(1,20,125).reshape(5,5,5)
print(a7)
print(len(a7))

[[[ 1.          1.15322581  1.30645161  1.45967742  1.61290323]
  [ 1.76612903  1.91935484  2.07258065  2.22580645  2.37903226]
  [ 2.53225806  2.68548387  2.83870968  2.99193548  3.14516129]
  [ 3.2983871   3.4516129   3.60483871  3.75806452  3.91129032]
  [ 4.06451613  4.21774194  4.37096774  4.52419355  4.67741935]]

 [[ 4.83064516  4.98387097  5.13709677  5.29032258  5.44354839]
  [ 5.59677419  5.75        5.90322581  6.05645161  6.20967742]
  [ 6.36290323  6.51612903  6.66935484  6.82258065  6.97580645]
  [ 7.12903226  7.28225806  7.43548387  7.58870968  7.74193548]
  [ 7.89516129  8.0483871   8.2016129   8.35483871  8.50806452]]

 [[ 8.66129032  8.81451613  8.96774194  9.12096774  9.27419355]
  [ 9.42741935  9.58064516  9.73387097  9.88709677 10.04032258]
  [10.19354839 10.34677419 10.5        10.65322581 10.80645161]
  [10.95967742 11.11290323 11.26612903 11.41935484 11.57258065]
  [11.72580645 11.87903226 12.03225806 12.18548387 12.33870968]]

 [[12.49193548 12.64516129 12.7983

## 11. randint()

It is an function. Which is present inside the random module in numpy library.

It is used to **generate random integer** number b/w the specified limit.

> ***Syntax :- ***

> ***np.random.randint(sv , ev+1 , no_of_parts )***

>***np.random.randint(sv , ev+1 , (no_of_rows , No_of_columns) )***

>***np.random.randint(sv , ev+1 , (slice , no_of_rows , No_of_columns) )***


In [ ]:
a8=np.random.randint(1,10,4)
print(a8)

[3 8 1 5]


## 12. rand()

It is an function. Which is present inside the random module in numpy library.

It is used to generate random integer number b/w **0-1**.

> ***Syntax :- ***

> ***np.random.rand(sv , ev+1 , no_of_parts )***

>***np.random.rand(sv , ev+1 , (no_of_rows , No_of_columns) )***

>***np.random.rand(sv , ev+1 , (slice , no_of_rows , No_of_columns) )***

In [ ]:
a8=np.random.rand(6)
print(a8)

a8=np.random.rand(6,6)
print(a8)

a8=np.random.rand(6,6,6)
print(a8)

[0.78338368 0.95587678 0.21719495 0.60927843 0.51885821 0.0038367 ]
[[0.23324041 0.06865326 0.93547895 0.51964669 0.77152224 0.19076838]
 [0.08445348 0.65717937 0.37631327 0.46821463 0.2654224  0.72950024]
 [0.01590466 0.56537555 0.26137872 0.04602725 0.77986682 0.18623967]
 [0.8981484  0.34321238 0.29205158 0.86875339 0.86376955 0.20344772]
 [0.847267   0.43149311 0.32937587 0.94011148 0.29737836 0.15152188]
 [0.20212371 0.52745542 0.95905981 0.09807047 0.23880727 0.98286737]]
[[[0.79201585 0.00787765 0.5907203  0.05234545 0.33207262 0.18686189]
  [0.18789527 0.32960091 0.51850552 0.93160376 0.95643234 0.64029853]
  [0.2054283  0.14741726 0.09879648 0.7988618  0.35804851 0.79565623]
  [0.66205109 0.85636533 0.59466632 0.83329288 0.1751718  0.57025367]
  [0.66583888 0.49185684 0.26284008 0.81767047 0.20823288 0.9339398 ]
  [0.43436577 0.71711005 0.63589531 0.7327175  0.73017927 0.73805543]]

 [[0.56023959 0.58500599 0.42654707 0.339479   0.2794958  0.15597246]
  [0.63253224 0.23605136 

## 13. randn()

It is an function. Which is present inside the random module in numpy library.

It is used to generate random integer number b/w **(-infinity) to (+infinity)**.

> ***Syntax :- ***

> ***np.random.randn(sv , ev+1 , no_of_parts )***

>***np.random.randn(sv , ev+1 , (no_of_rows , No_of_columns) )***

>***np.random.randn(sv , ev+1 , (slice , no_of_rows , No_of_columns) )***

In [ ]:
a8=np.random.randn(6)
print(a8)

a8=np.random.randn(6,6)
print(a8)


[-1.41803459  2.09226502  1.55565918 -0.49122509 -0.96235139  0.22667916]
[[-0.49276176 -0.8977535   0.89480983 -0.8222874  -0.75301704 -0.47749467]
 [-0.06199693  0.77921022 -0.07794335  1.42973839 -1.0769139  -1.15921537]
 [ 0.65119521 -0.80445611  0.25241834  0.91708261  0.48603937 -0.98876002]
 [-0.21253258  1.86240982 -1.6769707  -1.47909354 -0.69207351  1.57607239]
 [-1.89370121 -1.131327    0.43601116 -0.1975573   0.41016134 -1.90653802]
 [-0.27437074 -0.01503105 -0.37591563 -0.38272813  1.19585765  0.46952474]]


## 14. choice()

It is an function. Which is present inside the random module in numpy library.

It is used **to fetch random element** from the given array.

> ***Syntax :- np.random.choice(arr_vaar )***

note :- array must be 1D.

In [ ]:
a10 = np.array([1,2,4,8])
res = np.random.choice(a10)
print(res)

1


## 15. shuffle()

It is an function. Which is present inside the random module in numpy library.

It is used **to suffle the position of element** in the array.

> ***Syntax :- np.random.shuffle(arr_vaar )***

note :- It doesnt't have any return type.

In [ ]:
a10 = np.array([1,2,4,8])
np.random.shuffle(a10)
print(a10)

[4 8 2 1]


## 16. copy()

It is an function. Which is present inside the array module in numpy library.

It is used **to copy element** from one array to another array.

If we do modification on one array it won't effect the another arrray.

> ***Syntax :- arr_var.copy()***


In [ ]:
a10 = np.array([1,2,4,8])
a11 = a10.copy()
print(a10)
print(a11)

a10[3]=a10[1]+a10[2]+a10[3]
print(a10)
print(a11)

[1 2 4 8]
[1 2 4 8]
[ 1  2  4 14]
[1 2 4 8]


## 17. view()

It is an function. Which is present inside the numpy library.

It is used **to copy element** from one array to another array.

If we do modification on one array it will effect the another arrray.

> ***Syntax :- arr_var.view()***

In [ ]:
a10 = np.array([1,2,4,8])
a11 = a10.view()
print(a10)
print(a11)

a10[3]=a10[1]+a10[2]+a10[3]
print(a10)
print(a11)

[1 2 4 8]
[1 2 4 8]
[ 1  2  4 14]
[ 1  2  4 14]


## 18. zeros()

It is an function. Which is present inside the numpy library.

It is used to an array, which consist only **zeros**.

>***Syntax :-***

> ***a)np.zeros(no_of_value)***

> ***b)np.zeros(no_of_row , no_of_col)***

> ***c)np.zeros(slice, no_of_row , no_of_col)***



In [ ]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

## 19. ones()

It is an function. Which is present inside the numpy library.

It is used to an array, which consist only **ones**.

>***Syntax :-***

> ***a)np.ones(no_of_value)***

> ***b)np.ones(no_of_row , no_of_col)***

> ***c)np.ones(slice, no_of_row , no_of_col)***

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 20. identity()

It is an function. Which is present inside the numpy library.

It is used to create the identity matrix.

***Syntax :- np.identity(matrix_val / value)***

In [ ]:
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 21. Indexing

To fetch a particular elemnet  

In [ ]:
arr=np.array([[1,2,3,1],
             [4,5,6,2],
             [7,8,9,3],
             [7,8,9,3]])
print(arr[1][1])

5


## Slicing

To fetch the multiple values from the array we will use slicing.

In [ ]:
arr = np.array([1,2,4,'hi','bye'])

print(arr[0: :1])
print(arr[: :-1])

arr=np.array([[1,2,3,1],
             [4,5,6,2],
             [7,8,9,3],
             [7,8,9,3]])
print(arr[0:2:1,1:3:1])
# print(arr[: :-1])

['1' '2' '4' 'hi' 'bye']
['bye' 'hi' '4' '2' '1']
[[2 3]
 [5 6]]


In [ ]:
#slicing on 2d array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
# positve slicing
print(arr[0:2:1,0:2:1])
print('----------')
print(arr[0:3:1,1:2:1])
print('----------')
print(arr[1:2:1,1:2:1])
print('----------')
print(arr[0:3:2,0:3:2])
print('----------')
print(arr[1:2:1,0:3:2])
print('----------')
print(arr[0:3:,2::])
print('----------')
print(arr[0:3:2,0:3:1])
print('----------')
print(arr[0:3:1,0:3:2])
print('----------')
print(arr[0:1:1,0:1:1])
print('----------')
print(arr[0:2:,0:1:])
# negative slicing
print('----------')
na=arr[-2:-4:-1,-2:-4:-1]
print(na[::-1,::-1])
print(arr[-2:-4:-1,-2:-4:-1])

[[1 2]
 [4 5]]
----------
[[2]
 [5]
 [8]]
----------
[[5]]
----------
[[1 3]
 [7 9]]
----------
[[4 6]]
----------
[[3]
 [6]
 [9]]
----------
[[1 2 3]
 [7 8 9]]
----------
[[1 3]
 [4 6]
 [7 9]]
----------
[[1]]
----------
[[1]
 [4]]
----------
[[1 2]
 [4 5]]
[[5 4]
 [2 1]]


In [ ]:
#slicing on 3d array
arr = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]],
                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]])
print('----------1----------')
print(arr[0:3:1,0:1,0:3])
print('----------2----------')
print(arr[0:3:2,0:3:1,0:3:2])
print('----------3----------')
print(arr[0:3:2,0:3:2,0:3:2])

print('----------4----------')
print(arr[1:2,1:2,1:2])
print('----------5----------')
print(arr[0:3:1,0:3:2,1:2])
print('----------6----------')
print(arr[0:3:1,2,0:2:])

print('----------7----------')
print(arr[0:1:,0:1:,0:1:])
print('----------8----------')
print(arr[0:3:,1:2:,1:2:])
print('----------9----------')
print(arr[0:3:,1:2:,0:3:2])
print('----------10----------')
print(arr[0:3:,0:3:,2::])


----------1----------
[[[ 1  2  3]]

 [[10 11 12]]

 [[19 20 21]]]
----------2----------
[[[ 1  3]
  [ 4  6]
  [ 7  9]]

 [[19 21]
  [22 24]
  [25 27]]]
----------3----------
[[[ 1  3]
  [ 7  9]]

 [[19 21]
  [25 27]]]
----------4----------
[[[14]]]
----------5----------
[[[ 2]
  [ 8]]

 [[11]
  [17]]

 [[20]
  [26]]]
----------6----------
[[ 7  8]
 [16 17]
 [25 26]]
----------7----------
[[[1]]]
----------8----------
[[[ 5]]

 [[14]]

 [[23]]]
----------9----------
[[[ 4  6]]

 [[13 15]]

 [[22 24]]]
----------10----------
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## Operation on array (mathemetical)

In [ ]:
# 1d array
ar1 = np.array([1,2,3])
# 2d array
ar2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print('----------add----------')
print(ar1+ar2)
print('----------sub----------')
print(ar1-ar2)
print('----------mul----------')
print(ar1*ar2)
print('----------div----------')
print(ar1/ar2)
print('----------floor----------')
print(ar1//ar2)
print('----------rem----------')
print(ar1%ar2)
print('----------exp----------')
print(ar1**ar2)
# 3d array
ar3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]],
                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]])
print('----------add----------')
print(ar2+ar3)
print('----------sub----------')
print(ar2-ar3)
print('----------mul----------')
print(ar2*ar3)
print('----------div----------')
print(ar2/ar3)
print('----------floor----------')
print(ar2//ar3)
print('----------rem----------')
print(ar2%ar3)
print('----------exp----------')
print(ar2**ar3)

----------add----------
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
----------sub----------
[[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]
----------mul----------
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
----------div----------
[[1.         1.         1.        ]
 [0.25       0.4        0.5       ]
 [0.14285714 0.25       0.33333333]]
----------floor----------
[[1 1 1]
 [0 0 0]
 [0 0 0]]
----------rem----------
[[0 0 0]
 [1 2 3]
 [1 2 3]]
----------exp----------
[[    1     4    27]
 [    1    32   729]
 [    1   256 19683]]
----------add----------
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[11 13 15]
  [17 19 21]
  [23 25 27]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]]
----------sub----------
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ -9  -9  -9]
  [ -9  -9  -9]
  [ -9  -9  -9]]

 [[-18 -18 -18]
  [-18 -18 -18]
  [-18 -18 -18]]]
----------mul----------
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[ 10  22  36]
  [ 52  70  90]
  [112 136 162]]

 [[ 19  40  63]
  [ 88 115 144]
  [175 208 24

In [ ]:
# 1d array
ar1 = np.array([[1],
                [2],
                 [3]])
# 2d array
ar2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print('----------<----------')
print(ar1<ar2)
print('---------->----------')
print(ar1>ar2)
print('----------<=----------')
print(ar1<=ar2)
print('---------->=----------')
print(ar1>=ar2)
print('----------==----------')
print(ar1==ar2)
print('----------!=----------')
print(ar1!=ar2)

----------<----------
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
---------->----------
[[False False False]
 [False False False]
 [False False False]]
----------<=----------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
---------->=----------
[[ True False False]
 [False False False]
 [False False False]]
----------==----------
[[ True False False]
 [False False False]
 [False False False]]
----------!=----------
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#slicing on 1d array
ar1 = np.array([1,2,3])
#slicing on 2d array
ar2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print()

## In-built function in array.

arr-var.sum() -return summation.

arr-var.min() -return minimum.

arr-var.mix() -return maximum.

arr-var.mean() -return avarage.

arr-var.abs() -convert +ve values into _ve values.

